### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by lnguyen** [cloudfoundry-community/portcullis#4]

**Comment by thomasmitchell** [comment]
This is a very serious issue and our people are looking into it

**Comment by drnic** [comment]
Update on readme progress?

**Comment by thomasmitchell** [comment]
I'll whip up a short placeholder tonight. Right now the priority is getting the thing to actually do what I need it to do for a demo

**Comment by drnic** [comment]
Alert! Alert! There is now a readme.
